feat: add logstash-estates-to-es
ietty/Docker pull request #2
Opened 2020-02-24 16:17 UTC by sogaoh

logstash の container image base です
pipeline/main.conf が妥当そうかをご確認ください

2020-03-01 15:14 UTC, takemi-ohama approved these changes
遅くなってすみません！

2020-03-02 04:03 UTC, takemi-ohama requested changes
すみません。機密に近い情報までDockerfileに含める場合はhub.docker.comはふさわしくないので、別にリポジトリ用意してあります。
そちらに移動させていただければ

2020-03-02 04:03 UTC, takemi-ohama commented on logstash-estates-to-es/pipeline/main.conf
> +input {
このあたりのSQLまでDockerfileでコンパイルするなら、hub.docker.comのpublicリポジトリじゃダメですね...
private専用に `registry.ietty.estate` というのが準備してあるので、そちらを使ってください。

https://registry.ietty.estate/v2/_catalog?n=100
basic認証のパスワードはDMします。

2020-03-03 11:39 UTC, sogaoh commented on logstash-estates-to-es/pipeline/main.conf
> +input {
すみませんでした。このブランチ削除します。

2020-03-03 11:40 UTC, closed without merging